//
//  VerificationViewController.swift
//  ContractorApp2
//
//  Created by Zaizen Kaegyoshi on 12/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON

protocol VerificationDisplayLogic: class
{
    func displaySomething(viewModel: Verification.Something.ViewModel)
}

class VerificationViewController: UIViewController, VerificationDisplayLogic
{
    var interactor: VerificationBusinessLogic?
    var router: (NSObjectProtocol & VerificationRoutingLogic & VerificationDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = VerificationInteractor()
        let presenter = VerificationPresenter()
        let router = VerificationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        verify()
    }
    @IBOutlet weak var codeTextField: UITextField!
    func verify() {
        let url = "https://752a11b7.ngrok.io/twilio-sms/"
        var params: [String: Any] = ["phone_number": "5106761866"]
        
        Alamofire.request(url, method: .post, parameters: params).responseJSON { (response) in
            print(response.response)
            if let val = response.result.value {
                let json = JSON(val)
//                print(json)
                
                
            }
        }
        
    }
    @IBAction func verifyWithCode() {
        let url = "https://752a11b7.ngrok.io/twilio-verify/"
        var params: [String: Any]  = ["phone_number": "5106761866", "verification_code": self.codeTextField.text!]
        Alamofire.request(url, method: .post, parameters: params).responseJSON(completionHandler: { (response) in
            if let val = response.result.value {
                let json = JSON(val)
                if json["message"].stringValue == "Success" {
                    self.performSegue(withIdentifier: "Home", sender: self)
                }
            }
        })
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Verification.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Verification.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
