//
//  VerificationInteractor.swift
//  ContractorApp2
//
//  Created by Zaizen Kaegyoshi on 12/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerificationBusinessLogic
{
  func doSomething(request: Verification.Something.Request)
}

protocol VerificationDataStore
{
  //var name: String { get set }
}

class VerificationInteractor: VerificationBusinessLogic, VerificationDataStore
{
  var presenter: VerificationPresentationLogic?
  var worker: VerificationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Verification.Something.Request)
  {
    worker = VerificationWorker()
    worker?.doSomeWork()
    
    let response = Verification.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
