//
//  VerificationPresenter.swift
//  ContractorApp2
//
//  Created by Zaizen Kaegyoshi on 12/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerificationPresentationLogic
{
  func presentSomething(response: Verification.Something.Response)
}

class VerificationPresenter: VerificationPresentationLogic
{
  weak var viewController: VerificationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Verification.Something.Response)
  {
    let viewModel = Verification.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
