//
//  OnboardPresenter.swift
//  ContractorApp2
//
//  Created by Zaizen Kaegyoshi on 12/6/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardPresentationLogic
{
  func presentSomething(response: Onboard.Something.Response)
}

class OnboardPresenter: OnboardPresentationLogic
{
  weak var viewController: OnboardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Onboard.Something.Response)
  {
    let viewModel = Onboard.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
