//
//  OnboardInteractor.swift
//  ContractorApp2
//
//  Created by Zaizen Kaegyoshi on 12/6/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardBusinessLogic
{
  func doSomething(request: Onboard.Something.Request)
}

protocol OnboardDataStore
{
  //var name: String { get set }
}

class OnboardInteractor: OnboardBusinessLogic, OnboardDataStore
{
  var presenter: OnboardPresentationLogic?
  var worker: OnboardWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Onboard.Something.Request)
  {
    worker = OnboardWorker()
    worker?.doSomeWork()
    
    let response = Onboard.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
